### ISSUE TITLE
Plugin-descriptor not found during plugin installation

### ISSUE THREAD

**Issue by ersushantsood** [petaldevelopment/armor#12]
Hi I tried to install armor for 2.0 Elastic search and i am getting below error and as per elasticsearch 2.0 plugin documentation keeping plugin-descriptor in root directory of the plugin is mandatory but some how plugin tool is not taking the descriptor even if i manually place and again build the zip.  

./plugin install file:///armor2.1/target/releases/armor-2.0.0-SNAPSHOT.zip --verbose 
-> Installing from file:///armor2.1/target/releases/armor-2.0.0-SNAPSHOT.zip...
Trying file:///armor2.1/target/releases/armor-2.0.0-SNAPSHOT.zip ...
Downloading ........................................................................DONE
Verifying file:///armor2.1/target/releases/armor-2.0.0-SNAPSHOT.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by jmaitrehenry** [comment]
Fix on the last build (https://oss.sonatype.org/content/repositories/snapshots/com/petalmd/armor/2.0.0-SNAPSHOT/armor-2.0.0-20151216.195914-11.zip)

Thanks for the report!
