### ISSUE TITLE
elasticsearch plugin install fails with file not found exception

### ISSUE THREAD

**Issue by etfeet** [petaldevelopment/armor#5]
When attempting to install using elasticsearch plugin, elasticsearch plugin throws a file not found exception:

/usr/share/elasticsearch/bin/plugin -i com.petalmd/armor --verbose
-> Installing com.petalmd/armor...
Trying https://github.com/com.petalmd/armor/archive/master.zip...
Failed: IOException[Can't get https://github.com/com.petalmd/armor/archive/master.zip to /usr/share/elasticsearch/plugins/armor.zip]; nested: FileNotFoundException[https://github.com/com.petalmd/armor/archive/master.zip]; nested: FileNotFoundException[https://github.com/com.petalmd/armor/archive/master.zip];
Failed to install com.petalmd/armor, reason: failed to download out of all possible locations..., use --verbose to get detailed information

**Comment by jmaitrehenry** [comment]
You need to add the version: plugin -i com.petalmd/armor/1.7.0.

I will check for having it without version if it's possible.

Envoyé de mon iPhone

**Comment by etfeet** [comment]
that fixed it. thanks!
